In [1]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [2]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [3]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [4]:
#weight and bias initialization
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) ) 
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )

In [9]:
print(f'X.shape[1]= {X.shape[1]}')
print(f'wh = \n {wh}\n')
print(f'bh = \n {bh}\n')
print(f'wout = \n {wout}\n')
print(f'bout = \n {bout}\n')

X.shape[1]= 4
wh = 
 [[0.92741655 0.95329856 0.56415581]
 [0.41777829 0.22392873 0.41934048]
 [0.41378552 0.52094942 0.17167081]
 [0.83170563 0.531242   0.1766242 ]]

bh = 
 [[0.3125645  0.4175365  0.75440271]]

wout = 
 [[0.81042986]
 [0.3367345 ]
 [0.79920495]]

bout = 
 [[0.83061466]]



# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [13]:
for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 
   
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input=output_layer_input1+bout
    output=sigmoid( output_layer_input ) 

print(f'hiddenlayer_activations = \n {hiddenlayer_activations}\n')    
print ( "output of Forward Propogation:\n{}" .format(output)) 
print ( "wout,bout of Backpropagation:\n{},\n{}" .format(wout, bout ))

hiddenlayer_activations = 
 [[0.83939946 0.86895886 0.81611269]
 [0.92311707 0.91856642 0.84115586]
 [0.82664709 0.76363401 0.79418969]]

output of Forward Propogation:
[[0.92098011]
 [0.92826279]
 [0.91624718]]
wout,bout of Backpropagation:
[[0.81042986]
 [0.3367345 ]
 [0.79920495]],
[[0.83061466]]


In [14]:
B_wout = derivatives_sigmoid(wout)
B_bout = derivatives_sigmoid(bout)

In [15]:
print ( f"wout of Backpropagation:\n{B_wout}\n")
print ( f"bout of Backpropagation:\n{B_bout}\n")

wout of Backpropagation:
[[0.1536333 ]
 [0.22334438]
 [0.1604764 ]]

bout of Backpropagation:
[[0.14069394]]

